edgy/core/db/fields/base.py, edgy/core/db/fields/core.py, tests/contrib/multi_tenancy/test_mt_models.py, tests/fields/test_fields.py, tests/models/test_bulk_create.py, tests/models/test_bulk_update.py, tests/models/test_decimal_field.py, tests/tenancy/test_mt_bulk_create.py, tests/tenancy/test_mt_bulk_create_different_db.py, tests/tenancy/test_raise_assertation_error.py, tests/test_columns.py
- DecimalField was raising a `max_digits` constraint error
=> [Fix] - DecimalField

edgy/core/db/models/base.py, edgy/core/db/models/metaclasses.py, edgy/core/db/models/row.py, edgy/core/db/querysets/base.py, tests/contrib/multi_tenancy/test_tenant_models_using.py, tests/tenancy/test_tenancy_queries.py
* Making sure it queries always the tenant models
* Fixed queryset clone for those models
* Added tests
=> Fix multi tenancy query on tenancy models

pyproject.toml
Self referencing is cool but there is a better way sometimes
=> use features instead of self referencing

docs/queries/queries.md, edgy/__init__.py, edgy/core/db/models/metaclasses.py, edgy/core/db/querysets/__init__.py, edgy/core/db/querysets/clauses.py, edgy/core/signals.py, tests/clauses/test_and_clauses.py, tests/clauses/test_or_clauses.py
Changes:
- add Q logic
- allow building filters from kwargs
You missed django Q, do you?
=> add Q, extend and_ and or_

edgy/core/db/querysets/base.py, tests/integration/test_esmerald_create_and_return_model.py, tests/integration/test_esmerald_create_and_return_model_list_fk.py, tests/integration/test_esmerald_fk_reference_middleware.py, tests/integration/test_esmerald_tenant.py, tests/integration/test_esmerald_tenant_user.py
Changes:
- unified and_ and or_ handling (fixes deprecation warning for empty args)
- use httpx transport instead of app
=> fix deprecations, use clauses wrapper instead of plain sqlalchemy for unified and_ and or_ handling

edgy/core/db/models/base.py
Changes:
- ReflectModel has some dups and unused declarations, remove them
=> Remove unused or double declarations

edgy/contrib/multi_tenancy/models.py, edgy/core/db/models/base.py, edgy/core/db/models/model.py
Changes:
- change some Type[Model] to the correct type Model
- fix typo is_primrya or similar is wrong and is nowhere referenced
There is still some work to do.
=> fix typings, fix typo in is_primary

docs/fields.md, edgy/core/db/fields/core.py, edgy/core/db/models/base.py, tests/fields/test_composite_fields.py
CompositeField:
- add an overwrite for the BaseModel check. This way raw dicts can be injected in model_dump.
=> Feature: add unsafe json serialization

edgy/core/db/fields/base.py, edgy/core/db/fields/core.py, edgy/core/db/fields/foreign_keys.py, edgy/core/db/fields/many_to_many.py, edgy/core/db/fields/one_to_one_keys.py, edgy/core/db/fields/ref_foreign_key.py, edgy/core/db/models/base.py, edgy/core/db/models/metaclasses.py, tests/foreign_keys/test_foreignkey.py, tests/foreign_keys/test_many_to_many.py
Changes
- rework ForeignKeys to work with multiple primary keys. Untested yet.
- add field_name for getter/setters
- fix #101 
- use the descriptor protocol for many2many
- remove defunct (wrong type) and unused many_to_many collection
Missing
Tests
=> foreign keys on models with multiple primary keys

edgy/contrib/multi_tenancy/metaclasses.py, edgy/core/db/fields/base.py, edgy/core/db/fields/many_to_many.py, edgy/core/db/models/base.py, edgy/core/db/models/metaclasses.py, edgy/core/db/models/model.py, edgy/core/db/models/utils.py, edgy/core/utils/models.py, tests/fields/test_multi_column_fields.py
Changes:
- input transformation
- replace internal _check_registry by get_registry
=> Feature input bending

edgy/core/db/fields/base.py, edgy/core/db/models/metaclasses.py, edgy/core/tenancy/utils.py, pyproject.toml
Changes:
- set linting settings to the limits we discussed
- apply linting and manually fix long docstrings
=> Apply suggested linting settings

edgy/core/db/models/base.py, edgy/core/db/models/metaclasses.py
fix columns property, fix incorrect set up model references, fix extract_db_fields containing unrelated values
Fix #115
=> fix columns property, fix incorrect set up model references, fix extract_db_fields containing unrelated values

.github/workflows/publish.yml
Update the versions of the actions
Tests:
We can only see if this PR works when publishing. So we should include it short before a new release
=> update the used actions to their newest version for publish

edgy/conf/global_settings.py, edgy/core/db/querysets/base.py
Fixes issue with:
https://github.com/dymmond/edgy/discussions/116
and removes obsolete setting
=> fix primary key name different from id, remove obsolete setting

edgy/core/db/fields/core.py, edgy/core/db/models/metaclasses.py
Fixes:
- fix leftover without effect (field_name instead of name)
- fix ValidationError instead of silent ignore ExcludeField
=> Some small fixes

edgy/contrib/multi_tenancy/models.py, edgy/core/db/models/base.py, edgy/core/db/models/managers.py, edgy/core/db/models/metaclasses.py, edgy/core/db/models/model.py, edgy/core/db/relationships/related_field.py, tests/managers/test_managers_inherited.py, tests/models/test_embeddables.py
Fix manager initialization and inheritance
Add test for this.
=> Fix manager initialization and inheritance

docs/registry.md, edgy/cli/base.py, edgy/core/connection/registry.py, edgy/core/db/fields/base.py, edgy/core/db/models/base.py, edgy/core/db/models/metaclasses.py, edgy/core/utils/functional.py, edgy/core/utils/models.py, tests/models/run_sync/test_model_proxy.py, tests/models/test_lazyness.py, tests/models/test_model_proxy.py
Changes:
- proper document edgy_settr
- remove where not required
- allow controlling the lazyness (add helper function for registry)
- documentation regarding lazyness
=> Lazyness related fixes

docs/declarative-models.md, docs/fields.md, docs/migrations/migrations.md, docs/models.md, docs/queries/many-to-many.md, docs/queries/queries.md, docs/references/one-to-one.md, docs/relationships.md, docs/release-notes.md, docs/shell.md, docs/tenancy/contrib.md, edgy/core/db/fields/core.py, edgy/core/tenancy/utils.py, mkdocs.yml, tests/fields/test_fields.py, tests/fields/test_inheritance.py
Changes:
- correct binary field type
- add binary field to docs
- fix docs
- switch in fields.md to `` for parameters
=> fix binary field

docs/contributing.md
=> fixes to contributing.md

edgy/core/db/models/metaclasses.py, edgy/core/db/models/mixins/date_parser.py, edgy/core/db/models/mixins/row.py, edgy/core/db/models/model.py, edgy/core/db/querysets/base.py, tests/foreign_keys/test_foreignkey.py, tests/foreign_keys/test_foreignkey_unique_and_no_constraint.py, tests/tenancy/test_mt_bulk_create.py, tests/test_database_url.py, tests/uniques/test_unique.py, tests/uniques/test_unique_constraint.py, tests/uniques/test_unique_together.py
Changes:
- fix databasez 0.8 compatibility
- some small bugfixes
Missing:
- Real adaption, so jdbc connections are possible
=> Databasez compatibility fixes

edgy/core/db/models/mixins/row.py, edgy/core/db/querysets/base.py
Changes:
- make from_sqla_row async
- fix missing embed_parent call for get_or_none
=> Less nesting & missing embed_parent

edgy/core/utils/sync.py, edgy/utils/inspect.py
Changes:
- Try harder to stay in the same asyncio loop.
=> inspect & run_sync: try harder to stay in the same asyncio loop.

edgy/__init__.py
It changed already so much, we may should release a new version. Especially because of the backward incompatible stuff.
=> bump version

docs/relationships.md, docs/release-notes.md, edgy/__init__.py, edgy/core/db/models/base.py, pyproject.toml
Changes:
- fix load_recursive
- bump minimum version of databasez which contains important fixes concerning multi-loop safety
- bump version
=> fix load_recursive and multi-loop safety (bump databasez version)

docker-compose.yml
Can you please approve as soon as possible?
This is a security hole for developers. We need no release.
=> bind docker services to localhost (otherwise security hole for devs)

docs_src/tenancy/example/models.py, edgy/core/connection/registry.py, edgy/core/connection/schemas.py, edgy/core/db/context_vars.py, edgy/core/db/models/base.py, edgy/core/db/models/managers.py, edgy/core/db/models/metaclasses.py, edgy/core/db/models/mixins/reflection.py, edgy/core/db/models/mixins/row.py, edgy/core/db/models/types.py, edgy/core/db/querysets/base.py, edgy/core/db/querysets/mixins.py, edgy/core/tenancy/utils.py, edgy/core/utils/sync.py, edgy/utils/inspect.py, tests/fields/test_composite_fields.py
Changes:
- prepare for sync becoming independent from nest_asyncio (not activated because of bugs)
- fix tenancy using model classes as cache (very bad)
- make table_schema lru cached
- allow overwriting schema and setting it to the default schema via None (queryset)
- misc code hazard cleanups
- use more databasez direct instead of the engine
- disallow setting tables on model_class
=> progress sync & bugfixes (especially tenancy)

docs/models.md, docs/release-notes.md, edgy/__init__.py, edgy/core/db/models/base.py
Changes:
- add proper release notes
- document copying a model
=> version bump

docs/fields.md, docs/release-notes.md, edgy/core/db/fields/base.py, edgy/core/db/fields/foreign_keys.py, edgy/core/db/models/metaclasses.py, edgy/core/db/querysets/base.py, edgy/core/db/querysets/types.py, edgy/core/db/relationships/related_field.py, edgy/core/db/relationships/utils.py, tests/foreign_keys/test_cross_registry.py, tests/foreign_keys/test_cross_registry_and_db.py, tests/models/run_sync/test_model_values.py, tests/models/run_sync/test_model_values_list.py, tests/models/run_sync/test_models_filter.py, tests/models/test_model_values.py, tests/models/test_model_values_list.py, tests/models/test_models_filter.py
Changes:
- fix values and values_list
- add support for async functions as filter/or clauses
- add cross database capabilities for queries
=> fix values and values_list & can query across dbs

docs/fields.md, docs/release-notes.md, edgy/__init__.py, edgy/core/db/fields/base.py, edgy/core/db/fields/many_to_many.py, edgy/core/db/models/base.py, edgy/core/db/models/metaclasses.py, edgy/core/db/models/types.py
Changes:
- fix database appearing as value under some circumstances
- improve typings
- update documentation regarding fields and filefield workaround (revision)
- update release notes
=>  fix database appearing as value under some circumstances and typings

docs/fields.md, docs/queries/queries.md, docs/release-notes.md, edgy/core/db/context_vars.py, edgy/core/db/fields/file_field.py, edgy/core/db/models/base.py, edgy/core/db/models/model.py, edgy/core/db/models/types.py, edgy/core/db/querysets/base.py, edgy/core/files/base.py, tests/models/test_increment_onsave.py
Changes:
- make FileFields automatically revision safe
- fix bulk_update using wrong scope
- docs
=> FileFields automatic revision

docs/queries/queries.md, docs/release-notes.md, edgy/__init__.py, edgy/core/db/querysets/base.py, edgy/core/db/querysets/types.py
Changes:
- fix or clauses ignored in update and delete
- expose helper for integration in raw sqlalchemy queries
- add documentation for raw queries
- bump version
=> raw queries

docs/queries/queries.md, docs/release-notes.md, edgy/core/db/models/metaclasses.py, tests/test_migrate.py
Changes:
- test migrate against foreignkeys
- fix issue when using ForeignKey with makemigrate
- fix issue when having a ManyToMany field pointing to its owner
- add parameter for replacing relatedfields (not exposed yet and
defaults to False)
- update release notes
- document global or
=> fix makemigrate & more

docs/release-notes.md, edgy/core/db/fields/many_to_many.py, edgy/core/db/models/metaclasses.py, tests/foreign_keys/m2m_string/test_many_to_many.py, tests/foreign_keys/m2m_string/test_many_to_many_field.py, tests/foreign_keys/m2m_string/test_many_to_many_field_related_name.py, tests/foreign_keys/m2m_string/test_many_to_many_no_related_name.py, tests/foreign_keys/m2m_string/test_many_to_many_related_name.py
Changes:
- make ManyToMany lazy
- update release notes
=> Lazy ManyToMany fields

docs/models.md, docs/release-notes.md, edgy/core/db/models/base.py, tests/exclude_secrets/test_exclude_nested.py, tests/exclude_secrets/test_exclude_repeated.py, tests/exclude_secrets/test_secrets_fk.py
Changes:
- model_dump_json returns now the correct result
- document model_dump
- update tests
- show_pk False disables now `__show_pk__`
=> model dump fixes

docs/fields.md, docs/release-notes.md, edgy/__init__.py, edgy/core/db/fields/core.py, edgy/core/db/models/base.py, edgy/core/db/models/model.py, tests/fields/test_password_field.py
Changes:
- improve password field
- fix `__set__` incorrectly called on update/insert
=> improve pw field

edgy/cli/operations/shell/ipython.py, edgy/cli/operations/shell/ptpython.py, edgy/core/connection/schemas.py
Fix ipython and ptpython installation prompt. Bracket content is removed for unknown reasons
=> fix ipython and ptpython installation prompt 

docs/release-notes.md, edgy/core/db/constants.py, edgy/core/db/fields/many_to_many.py, edgy/core/db/relationships/related_field.py, edgy/core/db/relationships/relation.py
* Added new PROTECT and SET_DEFAULT for FKs
=> Remove warning on M2M

docs/release-notes.md, edgy/core/db/fields/foreign_keys.py, edgy/core/db/fields/many_to_many.py
Changes:
- warn if combination will likely break in ForeignKey
- remove unused Print import from ManyToMany
=> warn if combination will likely break in ForeignKey

pyproject.toml
=> fix project urls

docs/models.md, docs/release-notes.md, docs_src/models/constraints.py, edgy/core/db/datastructures.py, edgy/core/db/fields/composite_field.py, edgy/core/db/fields/core.py, edgy/core/db/fields/factories.py, edgy/core/db/fields/file_field.py, edgy/core/db/models/metaclasses.py, edgy/core/db/models/mixins/db.py, tests/fields/test_fields.py, tests/fields/test_multi_column_fields.py, tests/fields/test_url_field.py, tests/indexes/test_indexes_clauses.py, tests/metaclass/test_meta_errors.py, tests/test_constraints.py
Note this is for a 0.22.0 release
Changes:
- factory hooks receive a dictionary and can tweak the arguments passed down to the field
- fix unique handling
- allow passing plain constraints via meta
=> factory upgrade

docs/release-notes.md, edgy/__init__.py, edgy/cli/base.py, edgy/core/utils/sync.py
Fix migrate bug & bump version
=> Fix migrate bug

docs/models.md, docs/release-notes.md, edgy/contrib/contenttypes/fields.py, edgy/contrib/contenttypes/models.py, edgy/core/connection/registry.py, edgy/core/db/fields/base.py, edgy/core/db/fields/foreign_keys.py, edgy/core/db/fields/types.py, edgy/core/db/models/base.py, edgy/core/db/models/metaclasses.py, edgy/core/db/models/mixins/db.py, tests/contrib/contenttypes/test_contenttypes.py, tests/contrib/contenttypes/test_contenttypes_custom_non_abstract.py, tests/contrib/contenttypes/test_contenttypes_different_registry.py, tests/contrib/contenttypes/test_contenttypes_iterate.py, tests/metaclass/test_lazyness.py, tests/test_migrate.py
Changes:
- many fixes related to copying models
- add tests
- fix second migration bug
- fix migrating with content types
- lazyness related fixes (more performance)
=> Fix migration bug 2

docs/release-notes.md, edgy/conf/module_import.py
Changes:
- deprecate module_import
=> deprecate module_import

docs/release-notes.md, edgy/__init__.py
Changes:
- Fix version numbering
Apologies, the version numbers doesn't match. This PR fixes the numbering.
=> Version numbers mismatch

README.md
=> fix link to models

edgy/cli/templates/url/script.py.mako
Changes:
- fix incorrect inclusion of db password for hashing (netloc worked unexpectly)
- fix missing inclusion of database
=> fix url template

docs/tips-and-tricks.md, docs_src/tips/sandwich_main.py, docs_src/tips/sandwich_models.py
Changes:
- document the sandwich pattern
=> document the sandwich pattern

docs/release-notes.md, edgy/__init__.py, edgy/core/db/models/base.py, tests/models/test_model_class.py
Changes:
- fix comparation of models with non-models
- bump version
=> fix comparation of models with non-models

mkdocs.yml
It is no feature but core and is hard to find by the category
=> move connection section to core.

docs/connection.md, docs/release-notes.md, edgy/cli/operations/shell/ipython.py, edgy/cli/operations/shell/ptpython.py
Changes:
- fix DatabaseNotConnected warning in shell
- fix missing autoreflected models in shell
=> shell fixes

.pre-commit-config.yaml, docs/fields.md, docs/release-notes.md, edgy/core/db/fields/core.py, edgy/core/db/fields/many_to_many.py, edgy/core/db/models/base.py, edgy/core/db/models/metaclasses.py, edgy/testing/factory/utils.py, tests/models/test_model_class_mixed.py, tests/models/test_nested_dump.py, tests/models/test_select_related_nested.py
Changes:
- cleanup model_dump so it can also contain special fields
- add ref_foreign_key_fields for speeding up factories
- add needs_special_serialization property for optimizing the model_dump decision
Follow up PR to #272. Needs rebasing once #272 is merged
=> better model dump & add ref_foreign_key_fields

docs/fields/index.md, docs/fields/postgres.md, docs/models.md, docs/permissions/passwords.md, docs/queries/many-to-many.md, docs/queries/related-name.md, docs/queries/secrets.md, docs/reference-foreignkey.md, docs/reflection/reflection.md, docs/relationships.md, docs/release-notes.md, edgy/__init__.py, edgy/contrib/permissions/models.py, edgy/core/db/fields/__init__.py, edgy/core/db/fields/computed_field.py, edgy/core/db/fields/core.py, edgy/core/db/fields/mixins.py, edgy/core/db/fields/place_holder_field.py, edgy/core/db/fields/postgres.py, edgy/testing/factory/mappings.py, edgy/utils/inspect.py, mkdocs.yml, tests/fields/test_pg_array_field.py, tests/integration/test_esmerald_fk_reference_middleware.py, tests/reflection/test_table_reflection_special_fields.py, tests/test_lazy_imports.py
Changes:
- reorganizes fields and make them lazy
- add PGArrayField
- reorganize fields documentation
Fixes #242
=> Add PGArrayField

edgy/__init__.py
add fields for type checking/autocompletion in main `__init__`
=> add fields for type checking/autocompletion

compose.yml, docs/release-notes.md, docs/testing/model-factory.md, edgy/__init__.py, edgy/cli/base.py, edgy/testing/__init__.py, edgy/testing/factory/__init__.py, edgy/testing/factory/base.py, edgy/testing/factory/fields.py, edgy/testing/factory/metaclasses.py, edgy/testing/factory/subfactory.py, tests/factory/generation/test_basic_factory.py
- Brings the concept of a SubFactory and adds the almost same look and feel factory based on factory boy
=> SubFactory and Docs

Taskfile.yaml, docs/migrations/migrations.md, docs/release-notes.md, edgy/cli/decorators.py, edgy/cli/operations/init.py, edgy/cli/templates/sequencial/README, edgy/cli/templates/sequencial/alembic.ini.mako, edgy/cli/templates/sequencial/env.py, edgy/cli/templates/sequencial/generator.py, edgy/cli/templates/sequencial/script.py.mako, edgy/conf/global_settings.py, pyproject.toml
Adds a sequencial template for migrations allowing to be:
```shell
0001_something
0002_something_else
...
```
Updated mypy to the latest.
Add a taskfile
=> Add sequencial template

docs/release-notes.md, edgy/contrib/multi_tenancy/models.py, edgy/core/db/fields/core.py
I tried to fix the BooleanField typing long time ago but failed.
Thanks to #289 which failed the way I did, I found a way to have a bool typing.
=> fix BooleanField typing

edgy/core/db/querysets/base.py
This code leads to warnings with rollback and is easily fixable.
=> fix deadlock risk

tests/fields/test_fields.py
Changes:
- readd test to set minimum/maximum instead of the lte,lt,gt,gte
- don't use FloatField in integerfields test
- improve tests for decimal, float fields
=> update field tests

docs/release-notes.md, edgy/__init__.py, edgy/core/db/models/mixins/db.py, edgy/core/utils/db.py, tests/uniques/test_unique_together.py
Changes:
- fix unique_together naming leading to unidentifcatable names
- fix misleading prefix parameter in hash_names
=> fix unique_together naming

docs/release-notes.md, edgy/core/connection/registry.py, edgy/core/db/fields/composite_field.py, edgy/core/db/models/base.py, edgy/core/db/querysets/base.py, edgy/core/files/base.py
Changes
- FieldFile did use potential heavily blocking sync API in async code paths
- ruff formatting
=> FieldFile did use potential heavily blocking sync API in async code paths/ruff formatting

docs/pagination.md, docs/release-notes.md, docs_src/pagination/cursor_pagination.py, docs_src/pagination/double_linked_list.py, docs_src/pagination/simple_pagination.py, docs_src/pagination/using_attributes.py, docs_src/pagination/using_attributes_slow.py, edgy/contrib/pagination/__init__.py, edgy/contrib/pagination/base.py, edgy/contrib/pagination/counter.py, edgy/contrib/pagination/cursor.py, edgy/core/db/querysets/base.py, edgy/core/db/querysets/prefetch.py, edgy/core/db/querysets/types.py, edgy/core/marshalls/metaclasses.py, mkdocs.yml, tests/contrib/pagination/test_pagination.py, tests/contrib/pagination/test_pagination_reversed.py, tests/models/test_reverse.py
Changes:
- add paginators
- fix typing issue
- test reverse
=> add basic paginators

docs/pagination.md, docs/release-notes.md, docs_src/pagination/cursor_pagination.py, docs_src/pagination/esmerald_example.py, edgy/__init__.py, edgy/contrib/pagination/base.py, edgy/contrib/pagination/cursor.py, edgy/core/db/models/base.py, edgy/core/db/models/metaclasses.py, edgy/core/db/models/mixins/db.py, edgy/core/db/models/utils.py, edgy/core/db/relationships/relation.py, tests/contrib/multi_tenancy/test_tenant_models_using.py, tests/contrib/pagination/test_esmerald_integration_cursor.py, tests/contrib/pagination/test_pagination.py, tests/contrib/pagination/test_pagination_reversed.py
Changes:
- fix cursor backward navigation
- fix backward pages have flipped next/prev
- update docs
- add esmerald integration test
- rename to backward
- add reverse parameter for convert_to_page
- fix for pydantic 2.11 including previously excluded attributes
=> improve pagination docs, update tests, bugfixes for reverse     

.pre-commit-config.yaml, docs/release-notes.md, docs_src/pagination/esmerald_example.py, docs_src/pagination/simple_pagination.py, edgy/__init__.py, edgy/contrib/pagination/__init__.py, edgy/contrib/pagination/base.py, edgy/contrib/pagination/cursor.py, pyproject.toml, tests/contrib/pagination/test_esmerald_integration_cursor.py, tests/contrib/pagination/test_pagination.py
Changes:
- Split from Page and Paginator BasePaginator and BasePage.
- Add fields next_page, previous_page, current_page to Page.
- Add field current_cursor to CursorPage.
- Fix and improve pagination examples.
- bump version.
- bump ruff version
=> add more attributes to pages and split out BasePaginator

docs/release-notes.md, edgy/__init__.py, edgy/core/db/datastructures.py, edgy/core/db/querysets/base.py, edgy/core/db/querysets/mixins.py, tests/models/test_model_get_or_none.py, tests/querysets/test_queryset_class.py
Changes:
- fix partly broken caching
- add caching test
- rework QuerySetCache interface (for bugfixing)
- bump version
=> fix partly broken caching, add caching test

edgy/__init__.py, edgy/contrib/admin/templates/admin/base.html, edgy/contrib/admin/templates/admin/model_detail.html, edgy/contrib/admin/templates/admin/model_object_detail.html, edgy/contrib/admin/templates/admin/models.html, edgy/contrib/admin/utils/models.py, edgy/contrib/admin/views.py, edgy/contrib/contenttypes/models.py
Changes:
- highlight pks
- move pks in front for list
- exclude relation links in overview
- fix recent_models
- fix handling excluded fields
- fix deleting contenttypes with no valid attached model anymore
=> admin fixes

edgy/contrib/autoreflection/metaclasses.py, edgy/contrib/contenttypes/fields.py, edgy/contrib/contenttypes/metaclasses.py, edgy/contrib/multi_tenancy/metaclasses.py, edgy/core/db/fields/core.py, edgy/core/db/fields/exclude_field.py, edgy/core/db/fields/file_field.py, edgy/core/db/fields/foreign_keys.py, edgy/core/db/fields/image_field.py, edgy/core/db/fields/many_to_many.py, edgy/core/db/fields/mixins.py, edgy/core/db/fields/one_to_one_keys.py, edgy/core/db/fields/place_holder_field.py, edgy/core/db/fields/postgres.py, edgy/core/db/fields/ref_foreign_key.py, edgy/core/db/models/metaclasses.py, edgy/core/db/models/mixins/db.py, edgy/core/db/querysets/base.py, edgy/testing/factory/fields.py, edgy/testing/factory/utils.py, pyproject.toml
- fix typings for mypy 1.16
- update dependencies so mypy plugins can use the existing mypy in env (add to default)
- Remove old orjson-types
=> fix typings for mypy 1.16, which can infer more, improve some typings & add support for mypy checker plugins

edgy/core/db/fields/__init__.py, edgy/core/db/fields/postgres.py
- fix missing typing export
- modernize field: new description, future annotations and simplify init
=> fix missing typing export

docs/release-notes.md, edgy/__init__.py, edgy/cli/operations/admin_serve.py, edgy/core/db/models/mixins/admin.py, edgy/core/marshalls/config.py, edgy/core/marshalls/metaclasses.py, edgy/testing/factory/subfactory.py, edgy/utils/compat.py, pyproject.toml
Changes:
- Fix circular import error with marshalls
- improve description of admin_serve (was a bit mangled)
- bump version
- Use typeguard
=> fixes marshalls and admin serve

docs/release-notes.md, edgy/contrib/admin/templates/admin/base.html, edgy/contrib/admin/templates/admin/base_head.html, edgy/contrib/admin/templates/admin/model_object_create.html, edgy/contrib/admin/templates/admin/models.html, edgy/contrib/admin/views.py
Changes:
- Add models search
- split base.html for better customizations
=> admin: add models search, split base.html for better customizations

docs/release-notes.md
Sry the release note was too diffuse
=> fix rl note

docs/admin/admin.md, docs/release-notes.md, docs_src/admin/admin_embed.py, docs_src/admin/admin_embed_different_cookie.py, docs_src/admin/admin_embed_multiplexed.py, docs_src/admin/admin_permission.py, edgy/__init__.py, edgy/cli/operations/admin_serve.py, edgy/contrib/admin/templates/admin/base.html
=> fix admin behind a reverse proxy

.pre-commit-config.yaml, pyproject.toml
Changes:
- update ruff
- ruff pre-commit 
- add ruff formatting to pre-commit
=> update ruff, ruff pre-commit and add ruff formatting to pre-commit

docs/marshalls.md, docs/release-notes.md, edgy/contrib/admin/templates/admin/base.html, edgy/contrib/admin/templates/admin/base_definitions.html, edgy/contrib/admin/templates/admin/base_head.html, edgy/contrib/admin/templates/admin/model_object_create.html, edgy/contrib/admin/templates/admin/model_object_edit.html, edgy/contrib/admin/views.py, edgy/core/db/models/mixins/admin.py, edgy/core/files/base.py, edgy/core/marshalls/config.py, edgy/core/marshalls/metaclasses.py, tests/models/test_model_class.py, tests/test_columns.py
Changes:
- handle errors gracefully.
- add filters to marshalls
- improve admin UI
- use new marshall config in admin mixin to  remove fields
=> improve admin UI

docs/pagination.md, docs/release-notes.md, docs_src/pagination/double_linked_list.py, docs_src/pagination/simple_pagination.py, docs_src/pagination/using_attributes_slow.py, edgy/contrib/pagination/__init__.py, edgy/contrib/pagination/base.py, tests/contrib/pagination/test_pagination.py
Changes:
- add NumberedPaginator as alias
- add methods to resolve pages as dict
=> add NumberedPaginator alias, add dict methods

docs/fields/index.md, docs/queries/queries.md, docs/release-notes.md, edgy/core/db/fields/base.py, edgy/core/db/fields/core.py, edgy/core/db/fields/file_field.py, edgy/utils/inspect.py, tests/cli/main_json.py, tests/cli/test_json_to_jsonb.py, tests/fields/test_isempty_isnull.py, tests/reflection/test_table_reflection_special_fields.py
Changes:
- add isempty operator
- optimize json field for postgres
- raise NotimplementedError on misbehaving fields
=> isempty, add test cases, json field improvements

docs/release-notes.md, edgy/__init__.py
Make it a major release, so people are warned that some changes (actually fixes) could break things
=> make it a major

docs/fields/index.md, docs/permissions/passwords.md, docs/queries/prefetch.md, docs/queries/queries.md, docs/queries/related-name.md, docs/release-notes.md, docs/settings.md, docs_src/permissions/passwordretry.py, edgy/core/db/models/mixins/dump.py
Improve the PasswordField example
Improve the docs
=> improve example and some more doc stuff
