docs/managers.md
docs_src/models/managers/custom.py
docs_src/models/managers/example.py
docs_src/models/managers/override.py
edgy/core/db/fields/core.py
edgy/core/db/models/managers.py
edgy/core/db/models/metaclasses.py
tests/managers/test_manager_error.py
tests/managers/test_manager_simple.py

- Maximum recursion was being triggered when a manager was declared but not annotated with `ClassVar`.
Example
```python
import edgy
from edgy import Manager
from edgy.core.db.querysets import QuerySet
class UserManager(Manager):
def get_queryset(self) -> QuerySet:
queryset = super().get_queryset().filter(is_admin=False)
return queryset
class User(edgy.Model):
username: str = edgy.CharField(max_length=150)
is_admin: bool = edgy.BooleanField(default=True)
mang = UserManager()
class Meta:
registry = models
```
This causes a maximum recursion in the internal validations.
For the `managers` to be type annotated `ClassVar` and raise `ImproperlyConfigured` exception when that does not happen.

[Fix] - Maximum recursion for managers

---

docs_src/models/pk_with_default.py

In the current implementation of the Edgy ORM, the UUIDField throws an error when the max_length argument is included. Upon investigation, it was found that the UUIDField does not accept a max_length parameter, which is causing the issue.
To resolve this, I have removed the max_length argument from the UUIDField

Fix UUIDField max_length Argument Error in Edgy ORM asycpgn UUID does not has max_length

---

docs_src/models/unique_together/simple.py

Through [this ](https://edgy.tarsild.io/models/#simple-unique-together) example, the use of attribution `unique` is mentioned, but never actually used in the example.

Missing unique attribute for 'unique together'

---

edgy/cli/cli.py
edgy/core/db/models/base.py
edgy/core/db/models/metaclasses.py

Changes:
- add a class variable named `__reflected__`, this way we doesn't need to change anything else
<del>- fix some deprecation warnings</del>
- use and_ and or_ of the clauses module (can handle empty args)
- replace deprecated httpx app argument
Note: there should be also a small speed benefit by putting the model in the right registry in the first place

Feature:merged meta

---

pyproject.toml

Currently ruff can use the line length the user prefers (or which he accidentally activates) which leads to many changes in commits.
This PR directs ruff to use the line-length of 120 which is also specified in .editorconfig

Fix linting with ruff

---

docs/fields.md
edgy/core/db/fields/base.py
edgy/core/db/fields/core.py
edgy/core/db/fields/many_to_many.py
edgy/core/db/models/base.py
edgy/core/db/models/model.py

Changes:
- rename to_python to to_model and add phase as argument to it
- use expand_relationship only in BaseForeignKey and descendants and remove it from BaseField
TODO:
- find out why using settings in ManyToMany caused problems

Feature: rename to_python to to_model

---

docs/fields.md
docs/queries/prefetch.md
docs/release-notes.md
docs_src/prefetch/second/prefetch.py
docs_src/prefetch/second/prefetch_filtered.py
edgy/__init__.py
edgy/core/db/fields/base.py
edgy/core/db/fields/core.py
edgy/core/db/fields/many_to_many.py
edgy/core/db/models/base.py
edgy/core/db/models/managers.py
edgy/core/db/models/metaclasses.py
edgy/core/db/models/model.py
edgy/core/db/models/row.py
edgy/core/db/querysets/base.py
edgy/core/db/relationships/related_field.py
edgy/core/db/relationships/relation.py
edgy/core/utils/models.py
tests/prefetch/test_prefetch_related_nested.py

Changes:
- progress with multiple primary keys
- cleanup of related_fields
- allow multiple related_names with the same name to the same object
- slightly not documented yet Prefetch syntax change: you have to use the foreign key name when traversing a foreign key
- docs, changelog

foreign keys relation improvements

---

edgy/core/db/models/base.py
edgy/core/db/models/model.py
tests/models/test_model_multiple_primary_keys.py

remove `__model_references__` they are not needed at all and a source of errors
It is a radical simplification which saves also some CPU cycles by merging the setup from kwargs

remove `__model_references__`

---

docs/embedding.md
docs/fields.md
docs/models.md
docs/relationships.md
docs/release-notes.md
edgy/core/db/fields/__init__.py
edgy/core/db/fields/base.py
edgy/core/db/fields/composite_field.py
edgy/core/db/fields/core.py
edgy/core/db/fields/exclude_field.py
edgy/core/db/fields/factories.py
edgy/core/db/fields/foreign_keys.py
edgy/core/db/fields/many_to_many.py
edgy/core/db/fields/one_to_one_keys.py
edgy/core/db/fields/ref_foreign_key.py
edgy/core/db/models/base.py
edgy/core/db/models/metaclasses.py
edgy/core/db/models/row.py
edgy/core/db/querysets/base.py
edgy/core/db/relationships/related_field.py
tests/fields/test_embeddables.py
tests/fields/test_multi_column_fields.py
tests/foreign_keys/test_foreignkey_unique_and_no_constraint.py
tests/models/test_embeddables.py
tests/models/test_model_class.py

Changes:
- move is_required from baseCompositeField to implementers
- return empty values instead of raising NotImplementedError (reduces
boilerplate code)
- cleanup foreign keys, move logic for single foreign keys to foreign
keys
- allow selecting fields in manytomany keys
- allow passing an abstract model to through as a template
- fix metaclasses lazy setup
- remove useless validate
- improve base fields
- foreign keys use specified columns
- foreign key can skip constraint and optionally add index instead
Todo:
- <del>add tests and documentation</del>

Changes around fields, especially foreignKey fields

---

edgy/core/db/models/base.py
edgy/core/db/models/managers.py
edgy/core/db/models/metaclasses.py
tests/managers/test_manager_simple.py
tests/managers/test_managers.py

Now managers of an instance have also the attribute instance
I think this has potential. We could use managers as base for RelatedFields and Relations.
I splitted also Manager and BaseManager (without `__getattr__` magic)

managers with instance attribute

---

.github/workflows/test-suite.yml
docs/fields.md
docs/managers.md
docs/queries/related-name.md
docs/release-notes.md
edgy/core/db/fields/base.py
edgy/core/db/fields/factories.py
edgy/core/db/fields/foreign_keys.py
edgy/core/db/fields/many_to_many.py
edgy/core/db/fields/one_to_one_keys.py
edgy/core/db/models/metaclasses.py
edgy/core/db/models/row.py
edgy/core/db/querysets/base.py
edgy/core/db/relationships/related_field.py
edgy/core/db/relationships/relation.py
edgy/protocols/many_relationship.py
tests/foreign_keys/m2m_string/test_many_to_many_field.py
tests/foreign_keys/m2m_string/test_many_to_many_no_related_name.py
tests/foreign_keys/m2m_string/test_many_to_many_related_name.py
tests/foreign_keys/test_foreignkey.py

Changes
- allow skipping a RelatedField by specifying related_name=False
- can specify a reverse_name for allowing a backward relation
- Many2Many fields doesn't create an extra backward relation to the owner but specify instead reverse_name (see docs)
- ForeignKey have relation_fn argument which is used for creating the backward relation which is created by RelatedField
- this is used by M2M for initializing an ManyRelation on the reverse end
- m2m unique is used for target foreign key
- unique changes default related_name to singular
- update docs

Many2Many fixes

---

.github/workflows/test-suite.yml

base develop causes errors on scheduled action (at least for forks without develop branch)

github action: remove base develop from path filters

---

docs/fields.md
edgy/core/db/fields/foreign_keys.py
edgy/core/db/fields/many_to_many.py
edgy/core/db/models/row.py
edgy/core/db/querysets/base.py
edgy/core/db/relationships/relation.py
edgy/core/db/relationships/utils.py
tests/foreign_keys/test_foreignkey.py
tests/foreign_keys/test_foreignkey_deep_embed_parent.py
tests/foreign_keys/test_many_to_many_field.py
tests/models/run_sync/test_model_sqlalchemy.py
tests/models/test_model_sqlalchemy.py

Changes
- fix tests (inversion was never noticed)
- allow traversing nested attributes with embed_parent
- allow prefetching across unidirectional relations (and simplify it)
- prefetches are now handled in parallel
- use run_sync for prefetches instead of the loop stuff
- move crawl_relationship for preventing import loop
- remove extra
- cleanup queryset
- allow multiple clauses
- fix exclude not applied on clauses
- apply or or and on clauses too
- allow mixed clauses and kwargs

queryset updates, prefetch improvements

---

docs/fields.md
docs/release-notes.md
edgy/core/db/fields/base.py
edgy/core/db/fields/core.py
edgy/core/db/fields/many_to_many.py
edgy/core/db/models/model.py
edgy/core/db/querysets/base.py
edgy/core/utils/models.py
pyproject.toml
tests/fields/test_date_field.py
tests/fields/test_datetime_field.py
tests/fields/test_fields.py

Changes:
- one copy less for queries
- add `default_timezone`, `force_timezone`, `remove_timezone` to DateTimeField
- add `default_timezone`, `force_timezone` to DateField
- add `is_update` keyword argument to `get_defaults`
- remove internal helper for auto now
- add ConcreteAutoNow

timezone support

---

docs/release-notes.md
edgy/core/connection/registry.py
edgy/core/db/models/base.py
edgy/core/db/models/model.py
edgy/core/db/querysets/base.py
tests/fields/test_server_defaults.py

Changes
- Server defaults don't trigger load after saving (it would break defer).
- No nested run_sync calls when using embed_parent.
- No load triggers for fully initialized models.
- Add tests for server defaults.
In short: afterward there are no code paths in queries or models which use run_sync.
run_sync is still used when accessing non-initialized fields but not in the hot code pathes

Optimizations & server_defaults

---

edgy/cli/operations/shell/base.py
edgy/core/utils/sync.py
pyproject.toml
tests/cli/main.py
tests/cli/main_extra.py
tests/fields/test_composite_fields.py
tests/foreign_keys/test_many_to_many_field.py

Changes:
- remove nest_asyncio
- fixes for fixed TestClient (passes now correctly full_isolation and force_fallback through)
Note:
the tests run slightly slower. It is because of the full_isolation feature which is required for some tests with rollback.
One of the next step is to update the tests so the old performance is reached again.

remove nest_asyncio

---

docs/fields.md
docs/registry.md
docs/release-notes.md
edgy/core/connection/registry.py
edgy/core/db/fields/base.py
edgy/core/db/fields/core.py
tests/exclude_secrets/test_exclude.py
tests/models/run_sync/test_model_class.py
tests/models/run_sync/test_model_defer.py
tests/models/run_sync/test_model_get_or_none.py
tests/models/run_sync/test_model_only.py
tests/models/run_sync/test_model_values.py
tests/models/run_sync/test_model_values_list.py
tests/prefetch/test_prefetch_multiple_iterate.py

Changes:
- register_callback is now documented and has proper defaults for the one_time parameter
- DateTime fields save now the timezone (thx GladkovDO)
- field operators proper escape via autoescape where possible and escape themselves for iexact.

registry callback with default & fix for datetime field & fix for operators

---

docs/models.md
docs/release-notes.md
edgy/core/db/fields/file_field.py
edgy/core/db/fields/many_to_many.py
edgy/core/db/fields/types.py
edgy/core/db/models/base.py
edgy/core/db/models/metaclasses.py
edgy/core/db/models/mixins/__init__.py
edgy/core/db/models/mixins/db.py
edgy/core/db/models/model.py
edgy/core/db/models/types.py
edgy/core/marshalls/metaclasses.py
edgy/core/utils/models.py

Changes:
- move database related stuff in Model Mixin
- move metaclass from EdgyBaseModel to edgy.Model as well as some other attributes
- remove unused attribute with limited use parents from edgy MetaInfo
- improve multi_related attribute of MetaInfo by altering it so it contains the fk tuples which are set when used as a through model for ManyToMany fields
- deprecate `is_multi` there are no users and it can be evaluated as well by checking bool(multi_related)

Cleanup model inheritance & edgy can handle now future annotations

---

docs/models.md
docs/release-notes.md
edgy/contrib/autoreflection/metaclasses.py
edgy/contrib/multi_tenancy/models.py
edgy/core/db/fields/base.py
edgy/core/db/fields/file_field.py
edgy/core/db/fields/many_to_many.py
edgy/core/db/models/base.py
edgy/core/db/models/metaclasses.py
edgy/core/db/models/mixins/db.py
edgy/core/db/models/mixins/reflection.py
edgy/core/db/models/mixins/row.py
edgy/core/db/models/model.py

Changes:
- Allow stopping the retrieval of the registry from parents by setting registry = False.
- remove `__db_model__` it was serving a similar purpose but wasn't really configurable by users.

remove `__db_model__` and replace by registry = False

---

docs/queries/queries.md
docs/release-notes.md
edgy/core/db/models/mixins/db.py
edgy/core/db/models/mixins/row.py
edgy/core/db/querysets/base.py
edgy/core/db/querysets/clauses.py
edgy/core/db/querysets/mixins.py
edgy/core/db/querysets/prefetch.py
edgy/core/db/querysets/types.py
edgy/core/utils/db.py
tests/exclude_secrets/test_exclude_nested.py
tests/models/run_sync/test_models_filter.py
tests/models/test_model_queryset_update.py
tests/models/test_models_filter.py

Changes:
- fix query edge cases
- fix using using after filtering
- joins are now separated by prefix path (hashed)
- add local_or
- add second parameter for functions passed to filters

fix query edge cases

---

docs/queries/queries.md
docs/release-notes.md
edgy/core/db/models/mixins/row.py
edgy/core/db/querysets/base.py

Changes:
- fix queryset clone accidentally initializing table
- improve sql debug property
- update docs

Update docs & small fixes

---

docs/release-notes.md
edgy/cli/decorators.py

Changes:
- fix autodetection when having dotted directories in the cwd and edgy doesn't load before

fix autodetection when dotted directories are in the cwd

---

docs/fields.md
docs/queries/many-to-many.md
docs/queries/many-to-one.md
docs/release-notes.md
docs_src/queries/manytoone/example.py
edgy/core/db/relationships/relation.py
edgy/protocols/many_relationship.py
mkdocs.yml
tests/foreign_keys/test_foreignkey.py
tests/foreign_keys/test_many_to_many_field.py

Changes:
- add create to relations
- improve docs

add create method to relations

---

edgy/cli/templates/default/script.py.mako
edgy/cli/templates/plain/script.py.mako
edgy/cli/templates/url/script.py.mako
edgy/utils/hashing.py

Changes:
- remove double underscore (replaced by a single one)
- future proof hashed migrations

future proof hashed migrations / remove one underscore (no double underscore)

---

docs/migrations/migrations.md
edgy/cli/templates/default/script.py.mako
edgy/cli/templates/plain/script.py.mako
edgy/cli/templates/url/script.py.mako
tests/cli/main_multidb_nonidentifier.py
tests/cli/test_multidb_templates.py
tests/cli/test_templates.py
tests/settings/multidb_nonidentifier.py

Changes:
- db names are now in "" for handling confusing names like "another ".
- update tests and test for bad names
- improve docs, merge duplicate settings section in migrations.md

improve dbname styling / add tests for non-identifier names / improve docs

---

.github/workflows/test-suite.yml
.pre-commit-config.yaml

Changes:
- add py3.13 to the gh test matrix
- bump ruff pre-commit hook

test against py3.13, update ruff precommit hook

---

docs/connection.md
docs_src/connections/django.py
docs_src/connections/manual.py
docs_src/connections/manual_esmerald.py
tests/integration/test_esmerald_create_and_return_model.py
tests/integration/test_esmerald_create_and_return_model_list_fk.py
tests/integration/test_esmerald_fk_reference_middleware.py
tests/integration/test_esmerald_tenant.py
tests/integration/test_esmerald_tenant_user.py
tests/test_db_connected_warnings.py

Changes:
- improve connection docs
- test harder that the not connected warnings are appropriate.
- update tests which uses old style connections

update docs regarding connections and update related tests

---

docs/debugging.md
docs/fields.md
docs/release-notes.md
edgy/core/db/fields/many_to_many.py
edgy/core/db/models/base.py
edgy/core/db/models/mixins/row.py
edgy/core/db/querysets/base.py
edgy/core/db/relationships/relation.py
mkdocs.yml
tests/exclude_secrets/test_exclude.py
tests/foreign_keys/m2m_string_old/test_many_to_many.py
tests/foreign_keys/m2m_string_old/test_many_to_many_field.py
tests/foreign_keys/m2m_string_old/test_many_to_many_field_related_name.py
tests/foreign_keys/m2m_string_old/test_many_to_many_no_related_name.py
tests/foreign_keys/m2m_string_old/test_many_to_many_related_name.py
tests/foreign_keys/test_many_to_many_field_old.py
tests/foreign_keys/test_many_to_many_field_related_name_old.py
tests/foreign_keys/test_many_to_many_old.py
tests/foreign_keys/test_many_to_many_related_name.py
tests/foreign_keys/test_many_to_many_related_name_embedded.py
tests/foreign_keys/test_many_to_many_related_name_old.py
tests/models/test_model_class.py
tests/reflection/test_table_reflection.py
tests/reflection/test_table_reflection_schemes.py

Changes:
- Fix generic_field
- Fix traversing m2m fields is confusing because of an unusual default
- Fix exclude_secrets, don't load excluded fields on access
- Add debugging guide

change m2m traversing default, performance & accessing secrets doesn't trigger load

---

docs/connection.md
docs/queries/queries.md
docs/release-notes.md
docs_src/connections/asynccontextmanager.py
docs_src/connections/contextmanager.py
docs_src/connections/contextmanager_with_loop.py
docs_src/connections/contextmanager_with_loop_and_cleanup.py
edgy/core/connection/registry.py
edgy/core/utils/sync.py
tests/registry/test_registry_run_sync.py

Changes:
- add `with_async_env` method to registry
- `run_sync` reuses idling loops.
- `run_sync` uses the loop set by the Registry contextmanager `with_async_env`.

add with_async_env

---

docs/connection.md
docs/contributing.md
docs/release-notes.md
edgy/__init__.py
edgy/core/utils/sync.py
tests/registry/test_registry_run_sync.py

Changes:
- fix missing cleanup of subloops by polling (sry no better idea, the loop should have been collected)
- update docs
- bump version
This fixes a nasty testing bug
In practice this shouldn't have any bigger effects. Normally the loops are not changed that often.

fix missing cleanup of subloops

---

docs/release-notes.md
docs/testing/model-factory.md
docs_src/testing/factory/factory_exclude.py
docs_src/testing/factory/factory_mapping2.py
docs_src/testing/factory/factory_parametrize.py
docs_src/testing/factory/sequences.py
docs_src/testing/factory/sequences_even.py
docs_src/testing/factory/sequences_odd.py
docs_src/testing/factory/sequences_subfactory.py
edgy/testing/__init__.py
edgy/testing/factory/__init__.py
edgy/testing/factory/base.py
edgy/testing/factory/context_vars.py
edgy/testing/factory/fields.py
edgy/testing/factory/mappings.py
edgy/testing/factory/metaclasses.py
edgy/testing/factory/types.py
edgy/testing/factory/utils.py
tests/factory/test_factory.py
tests/factory/test_parameters.py

Changes:
- Replace Faker with ModelFactoryContext which is compatible to a Faker instance
- Add support for Sequences via get_callcount
- `exclude_autoincrement` is now also applied on subfactories thanks to the context

ModelFactoryContext instead of Faker parameter + we have now Sequences

---

docs/marshalls.md
edgy/core/marshalls/base.py
tests/marshalls/test_marshall_context.py

Sometimes there are cases when I want to enrich serialized data based on current context.
Changes:
- Added new property "context".
- Updated docs.

Provide additional context to marshall.

---

docs/release-notes.md
edgy/core/db/fields/core.py
tests/cli/main.py
tests/cli/test_nullable_fields.py

Changes:
automatically add a server_default for BooleanField default in case it is trivial. This fixes migrations.
In long term a generic solution is required.

fix booleanfield logic during migrations

---

docs/fields/index.md
docs/migrations/migrations.md
docs/release-notes.md
docs_src/models/constraints.py
edgy/conf/global_settings.py
edgy/core/connection/registry.py
edgy/core/db/fields/base.py
edgy/core/db/fields/core.py
edgy/core/db/fields/factories.py
edgy/core/db/fields/file_field.py
edgy/core/db/fields/foreign_keys.py
edgy/core/db/fields/many_to_many.py
edgy/core/db/fields/mixins.py
edgy/core/db/fields/types.py
pyproject.toml
tests/cli/main_server_defaults.py
tests/cli/test_nullable_fields.py
tests/cli/test_server_default_fields.py
tests/fields/test_fields.py
tests/settings/disabled_auto_server_defaults.py
tests/test_automigrations.py
tests/test_constraints.py

Changes:
- Convert for most fields defaults to server_default to ease migrations. There are some exceptions.
- Add the setting `allow_auto_compute_server_defaults` which allows to disable the automatic generation of server defaults.
- `get_default_value` is now also overwritable by factories.
- JSONField `default` is deepcopied to prevent accidental modifications of the default. There is no need anymore to provide a lambda.

add automatic generation of server_defaults for improving migrations

---

docs/queries/queries.md
docs/release-notes.md
edgy/core/db/querysets/base.py

Despite the root source wasn't found this fixes the `bulk_get_or_create` with edgy-guardian:
the force_fallback path is used (there shouldn't be many results either) and loads are now disabled. They shouldn't happen
for fields which are used for querying

fix bulk_get_or_create

---

docs/fields/index.md
docs/models.md
docs/release-notes.md
docs/signals.md
docs_src/signals/logic.py
edgy/contrib/contenttypes/models.py
edgy/core/db/fields/foreign_keys.py
edgy/core/db/fields/mixins.py
edgy/core/db/models/base.py
edgy/core/db/models/mixins/db.py
edgy/core/db/models/types.py
edgy/core/db/querysets/base.py
edgy/core/db/relationships/relation.py
tests/signals/test_deletion_signals.py
tests/signals/test_signals.py

Changes:
- Allow issuing signals during deletion when model based or virtual cascade deletion
- Align the delete signal interface with the save signal interface
- Signal Bugfixes
- Change raw_delete a little
- Remove loguru from tests, there was no reason for logging

align deletion signal interface with save interface & signal fixes

---

docs/release-notes.md
edgy/__init__.py
edgy/core/db/fields/base.py
edgy/core/db/fields/factories.py
edgy/core/db/fields/file_field.py
edgy/core/db/fields/types.py
tests/cli/test_multidb_templates.py
tests/cli/test_nullable_fields.py
tests/cli/test_nullable_generic_fields.py
tests/cli/test_server_default_fields.py
tests/cli/test_templates.py
tests/fields/test_multi_column_fields.py
tests/test_automigrations.py

Currently fields will cause an early settings import.
Despite this is not a big issue, it can be nasty and cause some wrong imports.
fix this by moving the server_default from init to an extra method and have an extra value Undefined for server_default.
cleanup also some tests

too early settings import

---

docs/release-notes.md
edgy/__init__.py
edgy/contrib/admin/application.py
edgy/contrib/admin/mixins.py
edgy/contrib/admin/templates/admin/model_object_create.html
edgy/contrib/admin/templates/admin/model_object_edit.html
edgy/contrib/admin/views.py

Changes
- Status code when page in admin was not found.
- Finally fix issues with json-editor ajax and enums by simply inlining all schemas and disabling ajax.
- For the json schema view: don't use ref_template, it isn't well supported and leads to problems with enums.

fix 404 status_code and fix json-editor with enums
